---

- name: install needed packages
  yum:
    name: '{{ item }}'
    state: installed
  with_items:
    - mariadb
    - mariadb-server
    - MySQL-python

- name: start mariadb-server
  service:
    name: mariadb.service
    enabled: yes
    masked: no
    state: started

- name: ensure database is present
  mysql_db:
    name: wordpress
    state: present

- name: ensure database user is present
  mysql_user:
    name: wordpress
    host: '{{ item }}'
    password: password
    priv: wordpress.*:ALL
  with_items:
    - "%"
    - localhost

