---

- name: set timezone to Asia/Tokyo
  timezone:
    name: Asia/Tokyo

- name: upgrade all packages
  yum:
    name: '*'
    state: latest

- name: install needed packages
  yum:
    name: '{{ item }}'
    state: installed
  with_items:
    - sysstat
    - net-tools
    - telnet
    - iotop
    - tmux
    - tcpdump

