---

- name: sshd conf
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#UseDNS'
    line: 'UseDNS no'
    backup: yes
  register: ssh_config

- name: restart sshd
  service:
    name: sshd
    state: restarted
  when: ssh_config.changed