# ref. https://docs.ansible.com/ansible/2.6/modules/win_domain_user_module.html
- hosts: windows
  gather_facts: false
  tasks:
  - name: set password
    set_fact:
      password: "{{ lookup('password', '/dev/null length=10 chars=ascii_letters,digits,hexdigits') }}"
  - name: print password
    debug:
      msg: "{{ password }}"
  tasks:
  - name: change password
    win_domain_user:
      name: "{{ user }}"
      password: "{{ password }}"
      path: "{{ path }}"
      update_password: always
  - name: sendmail
    script: SendMail_CreateUsers.ps1 "{{ user }}" "{{ password }}" "{{ sender }}" "{{ recipient }}" "{{ smtp_server }}" "{{ smtp_port }}"