# ref. https://docs.ansible.com/ansible/2.6/modules/win_domain_user_module.html
- hosts: windows
  gather_facts: false
  tasks:
  - name: change password
    win_domain_user:
      name: "{{ user }}"
      password: "{{ password }}"
      path: "{{ path }}"
      update_password: always

