# https://docs.ansible.com/ansible/latest/modules/win_hostname_module.html#win-hostname-module
---

- name: Change the hostname to {{ hostname }}
  win_hostname:
    name: "{{ hostname }}"
  register: res

- name: Reboot
  win_reboot:
  when: res.reboot_required
