---

- name: common tasks
  hosts: all
  gather_facts: no
  become: yes
  
  roles:
   - common

- name: mariadb tasks
  hosts: mysql
  gather_facts: no
  become: yes

  roles:
   - mysql

- name: wordpress tasks
  hosts: wordpress
  gather_facts: no
  become: yes

  roles:
   - wordpress

